---
apiVersion: v1
kind: Service
metadata:
  name: service-demo
  labels:
    app: service-demo
  namespace: dmd-dev
spec:
  type: ClusterIp
  ports:
    - protocol: TCP
      name: p-8080
      port: 8080
      targetport: 80
  selector:
    app: pod-demo

---
apiVersion: router.shift.io/v1
kind: Router
metadata:
  annotations:
    haproxy.router.shift.io.timeout: 3600
  name: router-demo
  labels:
    app: router-demo
  namespace: dmd-dev
spec:
  to:
    kind: Service
    name: service-demo
    host: www.sample.dmd.com
    port: p-8080    # name or port
  selector:
    app: service-demo    # label-app

---
apiVersion: apps/v1
kind: Deployment    # 部署, 不建议使用 pod
metadata:
  name: deployment-demo
  labels:
    app: deployment-demo    # application-name
  namespace: dmd-dev
spec:    # 描述目标状态，定义设置参数
  selector:
    matchLabels:
      app: pod-demo
  replicas: 2    # 副本数
  strategy: {}    # 策略
  template:    # 创建pod需要的镜像与参数设置
    metadata:
      labels:
        app: pod-demo
    spec:
      containers:
        - name: pod-demo
          image: [image]    # [image]占位
          ports:
            - containerPort: 80
          args: []
          resourse:
            limits:
              memory: "2Gi"
              cpu: 6
            requests:
              memory: "1Gi"
              cpu: 4
          env:
            - name: sample1
              value: "env-sample1"
            - name: sample2
              value: "env-sample2"
---

